### ISSUE TITLE
Volunteering to help maintain/caretake

### ISSUE THREAD

**Issue by mplscorwin** [nikclayton/ob-sql-mode#14]
Howdy!  I'm responding to the call for volunteers shared on the org-mode mailing list some time back.  Do you still need help (e.g.) reviewing and resolving issues?

I'm already involved with org development (tho I don't do that much as a worg curator) and I have FSF assignment for Emacs, should that be relevant now or in the future.

Private email or tagging me directly onto mailing list threads is fine.  I'm corwin AT bru DOT st.

**Comment by nikclayton** [comment]
Great -- I've just added you as a collaborator on the repository. When that's set up please feel free to run with it. I do very little with Org and Emacs at the moment, so I'd love to see this get attention from people who'd benefit from it.

**Comment by mplscorwin** [comment]
Thanks for the lightning fast response; I'll do my best!

**Comment by mplscorwin** [comment]
Now closing, but feel free to reopen (or create your own ticket) if you'd like to help!

**Comment by mplscorwin** [comment]
Now closing, but feel free to reopen (or create your own ticket) if you'd like to help!
