### ISSUE TITLE
Use sql-connection-alist for connections

### ISSUE THREAD

**Issue by conornash** [nikclayton/ob-sql-mode#3]
Is it possible to select an entry from the Emacs variable `sql-connection-alist` for connection details? This would make this package super useful for me, as all my SQL connection data is stored in a private file. That way I could share the queries and their results without sharing the credentials.

**Comment by indigoviolet** [comment]
This would be awesome.

**Comment by stardiviner** [comment]
I think it is possible. manage the variable `sql-connection-alist` and `ob-sql-mode` already has initialize product session function in https://github.com/nikclayton/ob-sql-mode/blob/master/ob-sql-mode.el#L207 `~org-babel-sql-mode-initiate-session`, in Org-mode keybinding it is `[C-c C-v C-z]`.
Need to push new connection to `sql-connection-alist`.

**Comment by stardiviner** [comment]
After test, seems `org-babel-sql-mode-initiate-session` has error:

```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  org-babel-sql-mode-initiate-session("test" ((:results . "replace") (:exports . "code") (:session . "test") (:product . "postgres") (:comments . "links") (:padline . "true") (:mkdirp . "yes") (:tangle . "no") (:noweb . "no") (:hlines . "no") (:cache . "yes")))
  funcall(org-babel-sql-mode-initiate-session "test" ((:results . "replace") (:exports . "code") (:session . "test") (:product . "postgres") (:comments . "links") (:padline . "true") (:mkdirp . "yes") (:tangle . "no") (:noweb . "no") (:hlines . "no") (:cache . "yes")))
```

**Comment by stardiviner** [comment]
Seems not compatible org-mode's `org-babel-initiate-session` command. argument number is wrong. I will dive into the source code to check out.

**Comment by stardiviner** [comment]
I fixed it, created PR at here https://github.com/nikclayton/ob-sql-mode/pull/4

**Comment by nikclayton** [comment]
Thanks, I've merged that in and pushed. If my understanding's correct this should show up on MELPA pretty soon.
