### ISSUE TITLE
Incompatibility with recent org-mode versions

### ISSUE THREAD

**Issue by ndokos** [nikclayton/ob-sql-mode#7]
Current versions of `org-mode` (9.2 for certain, perhaps earlier ones) have changed the structure of the `org-structure-template-alist` variable, so that lines 187-190 in `ob-sql-mode.el` cause errors when `ob-sql-mode` is loaded. See  [this question on the Emacs SE site](https://emacs.stackexchange.com/questions/49055/org-mode-9-2can-t-find-the-error-on-my-dot-emacs) for details.

**Comment by nikclayton** [comment]
Thanks for reporting this.
